### ISSUE TITLE
How about the implementations with CMAKE?

### ISSUE THREAD

**Issue by Tina1994** [eduardovera/D-KHT#4]
Hi, thanks for your open source for the depth plane detection.
I am using the Ubuntu18.04, and  I am doing some research which needs real time depth image segmentation. 
Could you provide cmake version code  for open? Thanks a lot.

**Comment by eduardovera** [comment]
Hi @Tina1994 ,

I'm currently finishing my PhD so I won't be able to provide it for the next few months. By the end of May I'll update the repository with the CMAKE version.

**Comment by eduardovera** [comment]
Hey @Tina1994 ,
updates: I didn't noticed before but @mikjh kindly worked on a code with CMAKE support. I'll accept his pull request in order to make it available. 

Best regards,

Eduardo.

**Comment by Tina1994** [comment]
Got it. Thanks a lot.
